from __future__ import annotations

import os
import re
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from .llm import llm
from .schemas import GlobalImagePlan, State
from .storage import allocate_output_slug, upsert_blog


def merge_content(state: State) -> dict:
    plan = state["plan"]
    if plan is None:
        raise ValueError("merge_content called without plan.")
    ordered_sections = [md for _, md in sorted(state["sections"], key=lambda x: x[0])]
    body = "\n\n".join(ordered_sections).strip()
    merged_md = f"# {plan.blog_title}\n\n{body}\n"
    return {"merged_md": merged_md}


DECIDE_IMAGES_SYSTEM = """You are an expert technical editor.
Decide if images/diagrams are needed for THIS blog.

Rules:
- Respect the requested maximum number of images.
- Each image must materially improve understanding (diagram/flow/table-like visual).
- Insert placeholders exactly: [[IMAGE_1]], [[IMAGE_2]], [[IMAGE_3]].
- If no images needed: md_with_placeholders must equal input and images=[].
- Avoid decorative images; prefer technical diagrams with short labels.
Return strictly GlobalImagePlan.
"""


def decide_images(state: State) -> dict:
    if not state.get("generate_images", True) or int(state.get("max_images", 3)) <= 0:
        return {
            "md_with_placeholders": state["merged_md"],
            "image_specs": [],
        }

    planner = llm.with_structured_output(GlobalImagePlan)
    merged_md = state["merged_md"]
    plan = state["plan"]
    assert plan is not None
    max_images = max(0, min(int(state.get("max_images", 3)), 3))

    image_plan = planner.invoke(
        [
            SystemMessage(content=DECIDE_IMAGES_SYSTEM),
            HumanMessage(
                content=(
                    f"Blog kind: {plan.blog_kind}\n"
                    f"Topic: {state['topic']}\n\n"
                    f"Generate images: {state.get('generate_images', True)}\n"
                    f"Max images: {max_images}\n\n"
                    "Insert placeholders + propose image prompts.\n\n"
                    f"{merged_md}"
                )
            ),
        ]
    )

    images = list(image_plan.images[:max_images])
    md_with_placeholders = image_plan.md_with_placeholders
    if len(image_plan.images) > max_images:
        for img in image_plan.images[max_images:]:
            md_with_placeholders = md_with_placeholders.replace(img.placeholder, "")

    return {
        "md_with_placeholders": md_with_placeholders,
        "image_specs": [img.model_dump() for img in images],
    }


def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")


def _safe_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^a-z0-9 _-]+", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s or "blog"


def _output_paths(title: str, output_slug: str | None = None) -> tuple[str, Path, Path]:
    slug = output_slug or _safe_slug(title)
    output_dir = Path("outputs") / slug
    images_dir = output_dir / "images"
    return slug, output_dir, images_dir


def _plan_payload(plan: object) -> object:
    if plan is None:
        return None
    if hasattr(plan, "model_dump"):
        return plan.model_dump()
    return plan


def save_blog_output(title: str, md: str) -> tuple[str, str]:
    output_slug, output_dir, _images_dir = _output_paths(title)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "blog.md").write_text(md, encoding="utf-8")
    return output_slug, str(output_dir)


def save_blog_manifest(title: str, md: str, state: dict) -> tuple[str, str]:
    requested_slug = (state.get("output_slug") or "").strip() or None
    output_slug, output_dir, _images_dir = _output_paths(title, requested_slug or allocate_output_slug(title))
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "blog.md").write_text(md, encoding="utf-8")
    plan = state.get("plan")
    upsert_blog(
        {
            "output_slug": output_slug,
            "title": title,
            "topic": state.get("topic"),
            "audience": state.get("audience"),
            "tone": state.get("tone"),
            "blog_length": state.get("blog_length"),
            "as_of": state.get("as_of"),
            "mode": state.get("mode"),
            "recency_days": state.get("recency_days"),
            "generate_images": state.get("generate_images", True),
            "max_images": state.get("max_images", 3),
            "final_md": md,
            "plan_json": _plan_payload(plan),
            "evidence_json": [e.model_dump() if hasattr(e, "model_dump") else e for e in (state.get("evidence") or [])],
            "sections_json": [[sid, section_md] for sid, section_md in (state.get("sections") or [])],
            "image_specs_json": state.get("image_specs") or [],
        }
    )
    return output_slug, str(output_dir)


def generate_and_place_images(state: State) -> dict:
    plan = state["plan"]
    assert plan is not None

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs", []) or []
    requested_slug = (state.get("output_slug") or "").strip() or None
    output_slug, output_dir, images_dir = _output_paths(plan.blog_title, requested_slug or allocate_output_slug(plan.blog_title))
    output_dir.mkdir(parents=True, exist_ok=True)

    # If no images requested, just write merged markdown
    if not image_specs:
        save_blog_manifest(plan.blog_title, md, state)
        return {"final": md, "output_slug": output_slug, "output_dir": str(output_dir)}

    images_dir.mkdir(parents=True, exist_ok=True)

    for spec in image_specs:
        placeholder = spec["placeholder"]
        filename = spec["filename"]
        out_path = images_dir / filename

        # generate only if needed
        if not out_path.exists():
            try:
                img_bytes = _gemini_generate_image_bytes(spec["prompt"])
                out_path.write_bytes(img_bytes)
            except Exception as e:
                # graceful fallback: keep doc usable
                prompt_block = (
                    f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
                    f"> **Alt:** {spec.get('alt','')}\n>\n"
                    f"> **Prompt:** {spec.get('prompt','')}\n>\n"
                    f"> **Error:** {e}\n"
                )
                md = md.replace(placeholder, prompt_block)
                continue

        img_md = f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*"
        md = md.replace(placeholder, img_md)

    save_blog_manifest(plan.blog_title, md, state)
    return {"final": md, "output_slug": output_slug, "output_dir": str(output_dir)}
